{% set name = "numba_celltree" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c73f17db7e2c3988d9fe57e231644220d366d0557bc08ee65c948a4e7d7a9c54

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - numba >=0.50
    - numpy

test:
  imports:
    - numba_celltree

about:
  home: https://github.com/deltares/numba_celltree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    Celltree data structure for searching for points, lines, boxes, and cells
    (convex polygons) in a two dimensional unstructured mesh.
  description: |
    Finding your way around in an unstructured meshes is difficult. Numba Celltree
    provides methods for searching for points, lines, boxes, and cells (convex
    polygons) in a two dimensional unstructured mesh.
  doc_url: https://deltares.github.io/numba_celltree/
  dev_url: https://github.com/deltares/numba_celltree

extra:
  recipe-maintainers:
    - Huite
